In [5]:
import numpy as np
arr=np.array([1,2,3,4,5,6,4])
print(arr)
x=np.where(arr==4)
print(x)
arr=np.array([1,2,3,4,5,6,8])
x=np.where(arr%2==0)
print(arr)
print(x)
arr=np.array([3,2,0,1])
print("\noriginal array",arr)
print("\nsorted array",np.sort(arr))
arr=np.array([[3,2,4],[5,0,1]])
print("\noriginal array",arr)
print("\nsorted array",np.sort(arr))

[1 2 3 4 5 6 4]
(array([3, 6]),)
[1 2 3 4 5 6 8]
(array([1, 3, 5, 6]),)

original array [3 2 0 1]

sorted array [0 1 2 3]

original array [[3 2 4]
 [5 0 1]]

sorted array [[2 3 4]
 [0 1 5]]
