In [6]:
import numpy as np
arr1=[10,20,30,40,50]
arr2=[3,4,5,7,10]
a=np.array(arr1)
b=np.array(arr2)
print("original arrays")
print(a)
print(b)
print("\n vector addition")
print(a+b)
print("\n vector subtraction")
print(a-b)
print("\n vector multiplication")
print(a*b)
print("\n vector division")
print(a/b)
print("\n vector dot product")
print(a.dot(b))
print("\n scalar multiplication")
sclr=5
print("scalar value=",sclr)

original arrays
[10 20 30 40 50]
[ 3  4  5  7 10]

 vector addition
[13 24 35 47 60]

 vector subtraction
[ 7 16 25 33 40]

 vector multiplication
[ 30  80 150 280 500]

 vector division
[3.33333333 5.         6.         5.71428571 5.        ]

 vector dot product
1040

 scalar multiplication
scalar value= 5
