In [11]:
  import numpy as np
a = np . array ([[1,2,3],[5,8,7]])
print ("Array created :\n",a)
b = np. array ((3,4))
print("Array with all zeroes :\n",b)
c = np . full ((3,3),6)
print("Array with all 6s:\n",c)
d = np.random . random((2,2))
print("Random array:\n",d)
import numpy as np
e = np. arange(0,30,5)
print(e)
arr = np.array([[1,2,3,4],[5,2,4,2],[1,2,0,1]])
newarr = arr.reshape (4,3)
print ("\n Original array :\n",arr)
print ("Reshaped array [4,3]:\n",newarr)
flarr = arr.flatten()
print ("\n Original array :\n",arr)
print ("\n flattened array :\n",flarr)
import numpy as np
arr = np. array([[1,2,3,4],[5,4,3,7],[6,7,0,1]])
print ("\n No of dimensions:\n", arr.ndim)
print("\n shape of array:\n",arr.shape)
print("\n size of array:\n",arr.size)
print("\n Array type:\n",arr.dtype)
newtype = arr.astype('f')
print("\n Converted array element:\n",newtype)
print("\n Converted array type:\n",newtype.dtype)
import numpy as np
p = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[3 : 0 : -1])
print(p[2,0:2])
print(p[2:,2:])
print(p[3:,3:])
print(p[:1,])
c=p.astype('f')
print(c)

Array created :
 [[1 2 3]
 [5 8 7]]
Array with all zeroes :
 [3 4]
Array with all 6s:
 [[6 6 6]
 [6 6 6]
 [6 6 6]]
Random array:
 [[0.01674754 0.9532407 ]
 [0.20989719 0.98796988]]
[ 0  5 10 15 20 25]

 Original array :
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array [4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]

 Original array :
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

 flattened array :
 [1 2 3 4 5 2 4 2 1 2 0 1]

 No of dimensions:
 2

 shape of array:
 (3, 4)

 size of array:
 12

 Array type:
 int64

 Converted array element:
 [[1. 2. 3. 4.]
 [5. 4. 3. 7.]
 [6. 7. 0. 1.]]

 Converted array type:
 float32
[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]]
[7 8]
[[ 9]
 [12]
 [15]]
[]
[[1 2 3]]
[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]
